version: '3.4'
services:
  web:
    # image: docker.io/mizanussayed/chatbot:v5
    build:
     context: ./src
     dockerfile: Dockerfile
    environment: 
      - "ConnectionStrings__DefaultConnection=Server=db; Database=ChatBot; User ID=sa; Password=${SA_PASSWORD}; TrustServerCertificate=True; MultipleActiveResultSets=true"
    ports:
      - "80"
    depends_on:
      - db
    restart: always
    networks:
      - appnet
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux
    ports:
      - "1433"

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: Express
    restart: always
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - appnet
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:

