version: '3.4'
services:
  web:
    image: docker.io/mizanussayed/chatbot:v5
    #build:
    #  context: ./src
    #  dockerfile: Dockerfile
    # environment:  # need to check again
    #   - ConnectionStrings_DefaultConnection=Server=db; Database=ChatBot; User ID=sa; Password=Mizanbro48&123; TrustServerCertificate=True; MultipleActiveResultSets=true
    ports:
      - "80"
    depends_on:
      - db
    restart: always
    networks:
      - appnet
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Mizanbro48&123"
      MSSQL_PID: Express
    restart: always
    volumes:
      - dbdata:/var/opt/mssql
    networks:
      - appnet
  nginx:
    image: nginx:alpine 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf.ro
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  dbdata:

